#include <QApplication>
#include <QObject>
#include <QWidget>
#include <QBoxLayout>
#include <QDesktopWidget>
#include <QFile>
#include <QJsonDocument>
#include <QLabel>
#include <QBitmap>
#include <QDebug>
#include <QtDBus>
