/* Generated by wayland-scanner 1.12.0 */

/*
 * Copyright (C) 2015 The Qt Company Ltd.
 * Contact: http://www.qt.io/licensing/
 *
 * This file is part of the examples of the Qt Wayland module
 *
 * $QT_BEGIN_LICENSE:BSD$
 * You may use this file under the terms of the BSD license as follows:
 *
 * "Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in
 * the documentation and/or other materials provided with the
 * distribution.
 * * Neither the name of The Qt Company Ltd nor the names of its
 * contributors may be used to endorse or promote products derived
 * from this software without specific prior written permission.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
 *
 * $QT_END_LICENSE$
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface qt_example_local_object_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *types[] = {
	NULL,
	&wl_surface_interface,
	&wl_surface_interface,
	NULL,
	&wl_surface_interface,
	NULL,
	&qt_example_local_object_interface,
	NULL,
	NULL,
	&wl_surface_interface,
	&wl_surface_interface,
	NULL,
};

static const struct wl_message qt_example_extension_requests[] = {
	{ "register_surface", "o", types + 1 },
	{ "bounce", "ou", types + 2 },
	{ "spin", "ou", types + 4 },
	{ "create_local_object", "nss", types + 6 },
};

static const struct wl_message qt_example_extension_events[] = {
	{ "close", "o", types + 9 },
	{ "set_font_size", "ou", types + 10 },
	{ "set_window_decoration", "u", types + 0 },
};

WL_EXPORT const struct wl_interface qt_example_extension_interface = {
	"qt_example_extension", 1,
	4, qt_example_extension_requests,
	3, qt_example_extension_events,
};

static const struct wl_message qt_example_local_object_requests[] = {
	{ "set_text", "s", types + 0 },
};

static const struct wl_message qt_example_local_object_events[] = {
	{ "clicked", "", types + 0 },
};

WL_EXPORT const struct wl_interface qt_example_local_object_interface = {
	"qt_example_local_object", 1,
	1, qt_example_local_object_requests,
	1, qt_example_local_object_events,
};

